sonar.projectKey=cicd-tasklist-frontend
sonar.projectName=cicd-tasklist-frontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.exclusions=src/__tests__/**,**/node_modules/**,**/dist/**,**/coverage/**
