sonar.projectKey=cicd-tasklist-frontend
sonar.projectName=cicd-tasklist-frontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_6f09b2fcaceee64c1e3918a49c7bfc106ee917b3
sonar.exclusions=src/__tests__/**,**/node_modules/**,**/dist/**,**/coverage/**
