sonar.projectKey=cicd-tasklist-frontend
sonar.projectName=cicd-tasklist-frontend
sonar.sources=src
sonar.tests=src/__tests__
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_6c850441ea26e17d93ece99405754430c9fd0a9b
sonar.exclusions=src/__tests__/**,**/node_modules/**,**/dist/**,**/coverage/**
